FROM huggingface/transformers-pytorch-gpu:latest
RUN apt update
RUN apt-get install -y libgl1-mesa-glx libglib2.0-0 git wget
WORKDIR /code
COPY requirements.txt .
RUN pip install --no-cache -r requirements.txt
WORKDIR /code/app
COPY experiments .
EXPOSE 8000
WORKDIR /code/app
COPY . .
ENTRYPOINT /bin/bash